### ISSUE TITLE
WakaTime: Invalid Api key. Make sure your Api key is correct.

### ISSUE THREAD

**Issue by AnimateXX** [wakatime/wakatime#221]
VSCode Insider, The Api key matches the value set on the web page。
VSCode can not work.

**Comment by AndreasSundman** [comment]
I have the same problem that started today (but in regular vs code). Tried generating new api key as well. Same error.

**Comment by haletsky** [comment]
Same problem with NeoVim started today.

**Comment by ApacheEx** [comment]
![image](https://user-images.githubusercontent.com/1918108/88525354-26a44300-d003-11ea-9bda-4daad4ba1b88.png)

since today's morning it doesn't work. I tried to re-generate keys, but no success. I use the latest stable VSCode

**Comment by MariusKuzminskas** [comment]
same here 
![image](https://user-images.githubusercontent.com/33681369/88528002-b39ccb80-d006-11ea-881b-cb0d2e79c6a0.png)
does not work even the api key is GOOD

**Comment by adelowo** [comment]
I have this same issue on Neovim and here is what I found, `bat ~/.wakatime.cfg`

```
       │ File: /Users/lanreadelowo/.wakatime.cfg
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [settings]
   2   │ debug = false
   3   │ hidefilenames = false
   4   │ ignore =
   5   │     COMMIT_EDITMSG$
   6   │     PULLREQ_EDITMSG$
   7   │     MERGE_MSG$
   8   │     TAG_EDITMSG$
   9   │ api_key=
  10   │ api_key=8e3c17d8-83d1-4ae5-aa0b-39da86059bcb


```

Maybe removing the empty `api_key` entry might resolve this, I am not to certain. Away from my mac now so I 
cannot test it out.

**Comment by adelowo** [comment]
I have this same issue on Neovim and here is what I found, `bat ~/.wakatime.cfg`

```
       │ File: /Users/lanreadelowo/.wakatime.cfg
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [settings]
   2   │ debug = false
   3   │ hidefilenames = false
   4   │ ignore =
   5   │     COMMIT_EDITMSG$
   6   │     PULLREQ_EDITMSG$
   7   │     MERGE_MSG$
   8   │     TAG_EDITMSG$
   9   │ api_key=
  10   │ api_key=xxxxx-xxxx-xxxx


```

Maybe removing the empty `api_key` entry might resolve this, I am not too certain. Away from my mac now so I 
cannot test it out.

**Comment by ApacheEx** [comment]
@adelowo, my cfg file looks good but still it's something else

```
[settings]
api_key = XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
status_bar_coding_activity = true
status_bar_enabled = true
```

**Comment by adelowo** [comment]
Yikes @ApacheEx 

I also tried to generate a new API key but the new key did not work either

**Comment by Mte90** [comment]
I have the same issue in Kate and NeoVim

**Comment by YouEclipse** [comment]
same err on wakatime API https://github.com/YouEclipse/wakatime-go/runs/913508896?check_suite_focus=true

**Comment by egordorichev** [comment]
Having the same issue with CLion & Bash integration

**Comment by bkhezry** [comment]
Same error in Android Studio.

**Comment by emacsified** [comment]
Same error here in Emacs.

**Comment by russeg** [comment]
eh don't try to "fix" this on your end, this is not an issue on our side lol.

**Comment by ikismail** [comment]
Same Issue here in VSCode. tried reinstalling the extension. API_KEY is same in dashboard.
turned on debug mode and find this erroes

```
[Extension Host] [WakaTime][ERROR] Error: Command failed: /XXXX/YYYYY/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli --today --plugin "vscode/1.47.2 vscode-wakatime/4.0.0"
[Extension Host] [WakaTime][ERROR] Invalid Api Key (104); Make sure your Api Key is correct!```

**Comment by igorskyflyer** [comment]
I can confirm having the same issue in (regular) VS Code since today, checked everything, my API key is correct.

**Comment by alanhamlett** [comment]
Sorry, this was me. 😭 I broke the api key parsing, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

**Comment by alichtman** [comment]
I am still seeing this behavior in `neovim` even though the plugin is fully updated. What should I do to fix this?
