### ISSUE TITLE
not logging with ST3 and wakatime >= 4.0.9

### ISSUE THREAD

**Issue by Tatarmalae** [wakatime/wakatime#33]
![screenshot](https://cloud.githubusercontent.com/assets/11876543/8984232/f781d0ba-36d8-11e5-92a5-f6198d26df9e.png)

**Comment by alanhamlett** [comment]
After setting `"debug": true` in your User WakaTime.sublime-settings file, do you see any error messages in your Sublime Console window?

Also can you `tail -f ~/.wakatime.log` and see if you are getting any error messages in the wakatime log file?

**Comment by Tatarmalae** [comment]
No, no error message.

**Comment by sgang007** [comment]
After opening the sublime editor, press Ctrl+` . Scroll and you should see
some error messages or else you will get the message 'Plugin Loaded'.
Increase the width of that console, take a screenshot and put it here.



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=gangulyshubhojyoti@gmail.com&idSignature=22>

On Fri, Jul 31, 2015 at 12:42 PM, Rustam <notifications@github.com> wrote:

> No, no error message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wakatime/wakatime/issues/33#issuecomment-126589521>.
>



-- 
Shubhojyoti

**Comment by Tatarmalae** [comment]
![waka](https://cloud.githubusercontent.com/assets/11876543/9010584/63b46fe0-37b0-11e5-8b4f-2616792e2369.png)

**Comment by alanhamlett** [comment]
So it's making the request, but not logging a response from the api. After reloading your .wakatime.log file in Sublime Text, do you see a debug line with a response code?

**Comment by alanhamlett** [comment]
The only thing I can think of that's changed in v4.0.9 is the requests library, so I've released a new version 4.0.10 with a downgraded requests library.

Can you upgrade to v4.0.10 of the Sublime Text plugin, restart ST and see if it's fixed?

**Comment by Tatarmalae** [comment]
4.0.10? I have a different version. Problem still exists ...
![screenshot_1](https://cloud.githubusercontent.com/assets/11876543/9032773/ab004c40-39ca-11e5-931e-056445b6f101.png)

**Comment by alanhamlett** [comment]
And no error messages in your `~/.wakatime.log` file? Do you have any offline heartbeats in your `~/.wakatime.db` slite3 database file?

**Comment by Tatarmalae** [comment]
And no error messages in your ~/.wakatime.log 
~ / .wakatime.db I can not see ...

**Comment by Tatarmalae** [comment]
Maybe it's the API? When entering the https://wakatime.com/api/v1/heartbeats there is an error: 
![errors](https://cloud.githubusercontent.com/assets/11876543/9055325/b6c925a6-3a92-11e5-90f6-2935b0a32951.png)

**Comment by alanhamlett** [comment]
`date` is only required with the `GET` request method, but heartbeats are sent using the `POST` method:
https://wakatime.com/developers/#heartbeats

**Comment by Tatarmalae** [comment]
Ok. I opened db file. 
![db](https://cloud.githubusercontent.com/assets/11876543/9056112/466d8430-3a99-11e5-9374-77c80bf9137f.png)

**Comment by alanhamlett** [comment]
What is the hostname of your computer? Those offline heartbeats are from yesterday (the `time` column is a unix epoch timestamp). Still not sure what is going wrong... can you double check for any error message in your Sublime Console after typing and saving a file?

**Comment by Tatarmalae** [comment]
![hostname](https://cloud.githubusercontent.com/assets/11876543/9056718/a792ced8-3a9d-11e5-8f02-5451b5e3f5f7.png)

**Comment by Tatarmalae** [comment]
Not working...

**Comment by Tatarmalae** [comment]
Well there, bro?

**Comment by Tatarmalae** [comment]
I found the reason! It is necessary that the computer name was not Cyrillic, and other character !!! Rename the computer, and it worked)
![screenshot_1](https://cloud.githubusercontent.com/assets/11876543/10662079/a0755b1a-78ba-11e5-9b4d-6eb15ada16c5.png)

**Comment by alanhamlett** [comment]
Ohhh, ok I'll fix this and write a test for it. Thanks for figuring it out!
